INSERT INTO smartbee.alerta_sugerencia (id,sugerencia) VALUES
	 ('HI-HAC-PI','1. Evaluar la posición relativa de las abejas respecto al sensor: durante el otoño e invierno, las abejas tienden a desplazarse hacia los sectores más cálidos dentro de la colmena. Este comportamiento puede alterar las lecturas del sensor y generar datos poco representativos de la temperatura o humedad general.
2. Gestionar el tamaño de la colmena en colonias grandes: en el caso de colmenas muy pobladas, es importante revisar su estructura y reducir el espacio si es necesario, retirando alzas que no estén en uso. Esto favorece la regulación térmica y el manejo interno por parte de la colonia.
3. Revisar el estado físico de la colmena: si la estructura presenta deterioro, grietas o exceso de humedad en la madera, se recomienda reemplazarla por una colmena en buenas condiciones para evitar problemas sanitarios y de aislamiento.
4. Evaluar la población presente: si la colonia cubre menos de cuatro marcos con abejas, se sugiere fusionarla con otra (solo si ambas están libres de enfermedades) o trasladarla a un cajón nucleador para facilitar su manejo y recuperación.
5. Revisar la ubicación del apiario: si el apiario está emplazado en zonas de vega, con escasa ventilación o rodeado de vegetación densa que favorece la acumulación de humedad, se recomienda trasladarlo a un lugar más seco y con mejor circulación de aire.'),
	 ('HI-HAP-PI','1. Gestionar el tamaño de la colmena en colonias grandes: en colmenas con alta población, es importante revisar el uso del espacio interior. Si hay alzas que no están siendo utilizadas, deben retirarse para optimizar la termorregulación y reducir la humedad interna.
2. Colocar cuña en las colmenas: instala una cuña que permita inclinar ligeramente la colmena hacia la piquera. Esto facilita la evacuación del agua acumulada en el interior, evitando problemas de humedad excesiva.'),
	 ('HI-HBC-PV','1. Entregar urgentemente fuentes de agua: cuando la humedad ambiental cae por debajo del 40%, la cría corre riesgo de deshidratación y la reina puede detener la postura. Es fundamental colocar recipientes con agua en el apiario, asegurándose de incluir sistemas de seguridad como piedras o flotadores para evitar el ahogamiento de las abejas.
2. Evaluar la ubicación del apiario: si las colmenas están expuestas a radiación solar directa durante largos periodos, se deben implementar mecanismos de sombreado, ya sea con mallas sombra o mediante el traslado a zonas con cobertura vegetal.'),
	 ('HI-HBP-PV','1. Mantener bebederos seguros en el apiario: coloca recipientes con agua de forma permanente, utilizando elementos como piedras o flotadores que permitan a las abejas acceder al agua sin riesgo de caer y ahogarse.'),
	 ('HIE-HAC','1. Detectar posibles causas sanitarias graves: cuando la humedad interna y externa de la colmena son iguales o muy similares, esto puede deberse a la mortandad de la colonia o a la presencia de enfermedades que afectan la capacidad de las abejas para regular la humedad interna. Entre los problemas sanitarios más comunes se encuentran Varroa y/o Nosema.
2. Visitar urgentemente el apiario: se debe acudir de inmediato al apiario y revisar las colmenas. Si se encuentran colonias muertas, es necesario retirar el material afectado para evitar el pillaje (robo de alimento por otras abejas), ya que esta situación puede facilitar la diseminación de enfermedades. Si aún hay abejas vivas —lo cual es poco frecuente en estos casos— se recomienda trasladarlas a cajas de menor tamaño para ayudarlas a conservar una humedad adecuada.
3. Evaluar la posición de las abejas respecto al sensor: durante el otoño e invierno, las abejas se agrupan en sectores más cálidos dentro de la colmena. Este desplazamiento puede interferir en la precisión de los datos entregados por el sensor, afectando la lectura de humedad real.'),
	 ('PE-CPA','1. Monitorear aumento de peso: un incremento en el peso de las colmenas durante los meses de noviembre a marzo indica almacenamiento de miel, la cual podrá ser cosechada.
2. Colocar alzas si no se puede cosechar: en caso de no realizar la cosecha a tiempo, visita el apiario y coloca alzas para entregar más espacio y permitir que las abejas sigan recolectando néctar.'),
	 ('PE-DP-PI','1. Revisar reservas de alimento: si las reservas están agotadas, se debe proporcionar alimentación sólida, idealmente utilizando miel almacenada, para asegurar la subsistencia de la colonia y el mantenimiento de su temperatura interna.
2. Evaluar condición sanitaria ante presencia de Varroa: si se detecta esta plaga, es fundamental aplicar un tratamiento sanitario durante el período de preparación para la invernada o durante la salida de la misma, según el momento del año en que se identifique.
3. Evaluar condición sanitaria ante presencia de Nosema: ante síntomas o diagnóstico de esta enfermedad, también se debe realizar el tratamiento sanitario correspondiente, durante los períodos críticos de entrada o salida de invernada.
4. Detectar y controlar casos de pillaje: si se observa pillaje, ajustar el listón guarda piquera para restringir el acceso al paso de una sola abeja. Revisa la colmena y reemplázala si está deteriorada. Además, cierra cualquier espacio por el cual pudieran estar ingresando abejas saqueadoras o chaquetas amarillas.'),
	 ('PE-E','1. Revisar colmenas cada 7–10 días: durante los meses de septiembre a diciembre, realiza inspecciones regulares eliminando celdas reales, previa confirmación de la presencia de reina, para evitar la enjambrazón.
2. Colocar alzas en colmenas desarrolladas: agrega alzas a colmenas que presentan un buen desarrollo poblacional. Esto previene la enjambrazón provocada por falta de espacio.
3. Aprovechar celdas reales para formar núcleos: si el objetivo es aumentar el número de colmenas, reemplazar colonias perdidas durante el invierno o renovar reinas envejecidas, utiliza celdas reales para formar núcleos nuevos.'),
	 ('TE-TA','1. Entregar más fuentes de hidratación externa: proporciona bebederos con agua ubicados fuera de la colmena, utilizando flotadores o piedras que permitan a las abejas acceder sin riesgo de ahogamiento.
2. A mediano plazo: instalar cerco vivo: considera la plantación de un cerco vivo alrededor del apiario. Esta barrera natural ayuda a moderar las fluctuaciones térmicas, reduciendo el impacto de temperaturas extremas sobre las colmenas.'),
	 ('TE-TB','1. Proteger la colmena del frío inmediato: utiliza algún sistema de aislación para reducir la exposición directa al frío. Esto puede incluir materiales aislantes o estructuras que disminuyan la pérdida de calor.
2. A mediano plazo: instalar cerco vivo: evalúa la implementación de un cerco vegetal como medida sostenible para atenuar los efectos del clima sobre las colmenas.
3. A mediano plazo: evaluar instalación de invernadero apícola: ante temperaturas extremas que pongan en riesgo la viabilidad de las colonias, considera la posibilidad de instalar un invernadero apícola que brinde condiciones más estables y protegidas durante el año.');
INSERT INTO smartbee.alerta_sugerencia (id,sugerencia) VALUES
	 ('TI-TAC','1.Revisión urgente del apiario: Si la temperatura interna supera los 40 °C, es fundamental acudir al apiario de inmediato. A esta temperatura, la cera comienza a ablandarse, perdiendo su estructura y provocando el colapso de los panales con miel. Esto puede bloquear la piquera, dificultar la ventilación y poner en riesgo la vida de la colonia por asfixia.
2. Retirar listón guarda piquera: Elimina el listón guarda piquera para facilitar el flujo de aire y permitir que las abejas mejoren la ventilación de la colmena por sus propios medios.
3. Evaluar la instalación de un alza: Revisa si es necesario poner un alza adicional. Esto ayudará a descongestionar la colmena, reducir la aglomeración de abejas y mejorar la circulación del aire en su interior.
4. Proveer fuentes adicionales de hidratación: Aumenta la disponibilidad de agua para las abejas. Puedes instalar un marco alimentador con agua dentro de la colmena o habilitar bebederos externos con flotadores o piedras que eviten el ahogamiento.
5. Generar sombra para reducir el estrés térmico: Protege las colmenas del sol directo usando malla sombra (evita las de color negro, ya que alteran a las abejas) o, si es posible, traslada las colmenas a un sector con sombra natural, como bajo árboles.'),
	 ('TI-TAP','1. Verificar tamaño del guarda piquera: revisa el tamaño del guarda piquera y, si es necesario, retíralo completamente para dejar la piquera abierta. Esto permitirá una mejor ventilación, ayudando a las abejas a regular la temperatura interna.
2. Evaluar instalación de alza adicional: considera colocar un alza si se detecta alta densidad de abejas dentro de la colmena. Esto contribuirá a reducir la aglomeración y facilitará la circulación de aire.
3. Revisar signos de enjambrazón: controla posibles señales de enjambrazón, ya que el aumento de temperatura interna puede estar relacionado con preparativos para dividir la colonia. La identificación temprana de este comportamiento es clave para la gestión del apiario.
4. Aumentar fuentes de hidratación: proporciona más puntos de acceso al agua para las abejas. Puedes colocar un marco alimentador con agua dentro de la colmena o instalar bebederos externos con sistemas de flotador o piedras para evitar que se ahoguen.'),
	 ('TI-TBC-PI','1. Revisar población de la colonia: si hay menos de cuatro marcos cubiertos con abejas, se recomienda fusionar con otra colonia o trasladar a un cajón nucleador, siempre que se haya descartado previamente la presencia de enfermedades. En caso de detectar problemas sanitarios, solo se debe realizar el cambio a cajón nucleo sin realizar fusiones.
2. Evaluar presencia de alimento: las abejas consumen miel para generar calor, por lo tanto, si no hay reservas suficientes, es necesario suplementar con alimento sólido o miel almacenada.
3. Ajustar el tamaño de la colmena en colonias grandes: en caso de colonias más pobladas, revisar si es necesario reducir el espacio interno retirando alzas que no estén siendo utilizadas. Esto permite conservar mejor el calor y optimizar la eficiencia térmica de la colonia.
4. Evaluar la posición de las abejas respecto al sensor: durante el otoño e invierno, las abejas tienden a desplazarse dentro de la colmena hacia sectores más cálidos. Este comportamiento puede afectar las lecturas del sensor y generar datos que no reflejan con precisión la situación interna real.'),
	 ('TIE-TAC','1. Detectar posibles causas sanitarias graves: cuando la temperatura interna y externa de la colmena son iguales o muy similares, esto puede indicar la mortandad de la colonia o la presencia de problemas sanitarios severos que estén afectando su capacidad de termorregulación. Entre las causas más comunes se encuentran enfermedades como Varroa y/o Nosema.
2. Visitar urgentemente el apiario: se debe acudir de inmediato al apiario y revisar las colmenas. Si se encuentran colonias muertas, retirar todo el material afectado para evitar el pillaje (robo de alimento por otras abejas), ya que este puede propagar enfermedades. Si aún quedan abejas vivas —lo cual es poco frecuente en estos casos— se recomienda trasladarlas a cajas de menor tamaño para facilitar la conservación del calor.
3. Evaluar la posición de las abejas respecto al sensor: durante el otoño e invierno, las abejas tienden a desplazarse hacia las zonas más cálidas del interior de la colmena. Este comportamiento puede interferir en el monitoreo, afectando la precisión de las lecturas del sensor.');
